# Generated by Django 5.1 on 2024-09-16 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tags', '0002_alter_tag_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaggItem',
            new_name='TaggedItem',
        ),
    ]
